//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 高校教材管理系统.rc
//
#define IDOK3                           2
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDOK4                           4
#define IDOK5                           5
#define IDOK6                           6
#define IDOK7                           7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MYTYPE                      129
#define IDB_BIXIU1                      131
#define IDB_BIXIU2                      132
#define IDB_BIXIU3                      133
#define IDB_BIXIU4                      134
#define IDB_BIXIU5                      135
#define IDD_DENGLU                      136
#define IDB_DENGLUJIEMIAN               138
#define IDD_ZHUCE                       139
#define IDD_BENXUEQISUOXUJIAOCAI        140
#define IDD_XIUGAIGERENXINXI            141
#define IDD_YONGHUGENGGAIMIMA           142
#define IDD_JIAOCAITUIDING              143
#define IDD_LIANXIGUANLIYUAN            144
#define IDD_JIAOCAIJIBENXINXI           145
#define IDD_JIAOCAIJINHUO               146
#define IDD_JIAOCAICHUKU                147
#define IDD_KUCUNGUANLI                 148
#define IDD_KUWEIGUANLI                 149
#define IDD_GENJUJIAOCAOHAO             150
#define IDD_GENJUJIAOCAIMING            151
#define IDD_FENLEIXUANZEYUDING          152
#define IDD_CAHKANSUOYOUJIAOCAI         153
#define IDD_JINHUOCAIWUGUANLI           154
#define IDD_CHUHUOCAIWUGUANLI           155
#define IDD_YUEFENCAIWUGUANLI           156
#define IDD_NIANFENCAIWUGUANLI          157
#define IDD_YINGLIZONGBIAO              159
#define IDD_YONGHUGERENGUANLI           160
#define IDD_BANJIFUZERENGUANLI          161
#define IDD_ZHUCEBANJIFUZEREN           162
#define IDD_GONGYINGSHANGGUANLI         163
#define IDD_ZHUCEGONGYINGSHANG          164
#define IDD_CHUBANSHEGUANLI             165
#define IDD_ZHUCECHUBANSHE              166
#define IDD_ZHUCEGUANLIYUAN             167
#define IDD_XIUGAIGUANLIYUANMIMA        168
#define IDD_XIUGAIYONGHUJIBENXINXI      169
#define IDD_YONGHUXIAOXI                170
#define IDC_EDIT_YONGHUMING             1000
#define IDC_EDIT_MIMA                   1001
#define IDC_BUTTON_DENGLU               1004
#define IDC_BUTTON_ZHUCE                1005
#define IDC_EDIT1                       1006
#define IDC_EDIT2                       1007
#define IDC_EDIT3                       1008
#define IDC_EDIT4                       1009
#define IDC_EDIT5                       1010
#define IDC_EDIT6                       1011
#define IDC_EDIT7                       1012
#define IDC_EDIT8                       1013
#define IDC_EDIT9                       1014
#define IDC_EDIT10                      1015
#define IDC_EDIT11                      1016
#define IDC_EDIT12                      1017
#define IDC_COMBO1                      1018
#define IDC_EDIT13                      1018
#define IDC_COMBO2                      1019
#define IDC_EDIT14                      1019
#define IDC_EDIT15                      1020
#define IDC_BUTTON1                     1021
#define IDC_BUTTON2                     1022
#define IDC_BUTTON4                     1023
#define IDC_TAB1                        1024
#define IDC_BUTTON6                     1024
#define IDC_LIST1                       1025
#define IDC_BUTTON3                     1027
#define IDC_DATETIMEPICKER1             1029
#define IDC_BUTTON5                     1030
#define IDC_LIST2                       1031
#define IDC_EDIT_QUERENMIMA             1032
#define IDC_EDIT_XINGMING               1033
#define IDC_EDIT_LIANXIFANGSHI          1035
#define IDC_EDIT_ZHUANYE                1036
#define IDC_DATETIMEPICKER              1037
#define IDC_EDIT_BEIZHU                 1038
#define IDC_STATIC_TOUXIANG             1039
#define IDC_BUTTON_XUANZETOUXIANG       1040
#define IDC_BUTTON_QUXIAOXUANZETOUXIANG 1041
#define IDC_BUTTON_XIUGAI               1042
#define IDC_BUTTON_QUXIAO               1043
#define IDC_STATIC_XUANZETOUXIANG       1045
#define IDC_COMBO_XINGBIE               1046
#define IDC_BUTTON_HUOQUWODEXINXI       1047
#define IDC_EDIT_JIUMIMA                1048
#define IDC_EDIT_XINMIMA                1049
#define IDC_EDITCHONGFUXINMIMA          1050
#define IDC_COMBO_CHAXUNTIAOJIAN        1051
#define IDC_EDIT_CHAXUNNEIRONG          1052
#define IDC_BUTTON_CHAXUN               1053
#define IDC_EDIT_ZHIDUJIAOCAIMINGCHENG  1054
#define IDC_EDIT_ZHIDUJIAOCAIBIANHAO    1055
#define ID_MENU_JIAOCAIJIBENXINXI       32771
#define ID_MENU_JIAOCAIJINHUO           32772
#define ID_MENU_JIAOCAICHUKU            32773
#define ID_MENU_KUCUNGUANLI             32774
#define ID_MENU_KUWEIGUANLI             32775
#define ID_MENU_GENJUJIAOCAIHAOYUDING   32776
#define ID_MENU_GENJUJIAOCAIMINGYUDING  32777
#define ID_MENU_FENLEIXUANZEYUDING      32778
#define ID_MENU_CHAKANSUOYOUJIAOCAI     32779
#define ID_MENU_CHAKANBENXUEQISUOXUJIAOCAI 32780
#define ID_MENU_XIUGAIGERENXINXI        32781
#define ID_MENU_GENGGAIMIMA             32782
#define ID_MENU_QIEHUANYONGHU           32783
#define ID_MENU_TUICHUDENGLU            32784
#define ID_MENU_JINHUOCAIWUGUANLI       32785
#define ID_MENU_CHUHUOCAIWUGUANLI       32786
#define ID_MENU_YUEFENCAIWUGUANLI       32787
#define ID_MENU_NIANFENCAIWUGUANLI      32788
#define ID_MENU_YINGLIZONGBIAO          32789
#define ID_MENU_BANJIFUZERENGUANLI      32790
#define ID_MENU_YONGHUGERENGUANLI       32791
#define ID_MENU_GONGYINGSHANGGUANLI     32792
#define ID_MENU_CHUBANSHEGUANLI         32793
#define ID_MENU_XIUGAIGUANLIYUANMIMA    32794
#define ID_MENU_ZHUCEXINGUANLIYUAN      32795
#define ID_MENU_XIUGAIYONGHUJIBENXINXI  32796
#define ID_MENU_YONGHUXIAOXI            32797
#define ID_MENU_LIANXIGUANLIYUAN        32800
#define ID_MENU_JIAOCAITUIDING          32801
#define ID_MENU_BANGZHU                 32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
